version: '3.2'
services:
  app:
    image: "hezr/brew_dash"
    # build: "."
    user: elixir:elixir
    volumes:
      - ./data:/data/
    ports:
      - ${EXT_PORT:-80}:${PORT:-4000}
    environment:
      - PORT=${PORT:-4000}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - GRAINFATHER_USERNAME=${GRAINFATHER_USERNAME}
      - GRAINFATHER_PASSWORD=${GRAINFATHER_PASSWORD}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    restart: always
