version: '3.2'
services:
  app:
    image: "hezr/brew_dash"
    # build: "."
    volumes:
      - ./data:/data/
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    environment:
      - PORT=${PORT:-4000}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - GRAINFATHER_USERNAME=${GRAINFATHER_USERNAME}
      - GRAINFATHER_PASSWORD=${GRAINFATHER_PASSWORD}
