version: '3.2'
services:
  app:
    image: "hezr/brew_dash"
    #build: "."
    volumes:
      - ./data:/data/
    ports:
      - "4000:4000"
    command: "bin/brew_dash start"
    environment:
      - SECRET_KEY_BASE=test
